export const MAX_TEMPLATES = 100;
export const CACHE_BUST_PERIOD = 1000 * 60 * 2
export const UPDATE_PERIOD_MILLIS = 100
export const SECONDS_SPENT_BLINKING = 5;
export const AMOUNT_OF_BLINKING = 11
export const ANIMATION_DEFAULT_PERCENTAGE = 1/3